export const INIT_TEAM_MEMBERS = "INIT_TEAM_MEMBERS";
export const INIT_BOARD_MEMBERS = "INIT_BOARD_MEMBERS";
export const INIT_BYOB_SPEAKERS = "INIT_BYOB_SPEAKERS";

export const TOGGLE_MENU = "TOGGLE_MENU";

export const INIT_POSTS = 'INIT_POSTS';
export const POSTS_PAGINATION = 'POSTS_PAGINATION';
export const SINGLE_POST = 'SINGLE_POST';
export const POSTS_CATEGORIES = 'POSTS_CATEGORIES';
export const FIND_POSTS_BY_CATEGORY = 'FIND_POSTS_BY_CATEGORY';
export const SEARCH_POSTS = 'SEARCH_POSTS';

export const INIT_EVENTS = "INIT_EVENTS";
export const SEARCH_EVENTS = "SEARCH_EVENTS";
export const PAGINATION = "PAGINATION";

export const INIT_SUCCESS_STORIES = 'INIT_SUCCESS_STORIES';
export const INIT_FAQ = 'INIT_FAQ';
export const INIT_PRIVACY_POLICIES = 'INIT_PRIVACY_POLICIES';
export const INIT_CODE_OF_CONDUCT = 'INIT_CODE_OF_CONDUCT';
export const INIT_VALUES = 'INIT_VALUES';
export const INIT_TERMS = 'INIT_TERMS';
export const INIT_DATA_DESCRIPTION = 'INIT_DATA_DESCRIPTION';
export const SERVICES_FAQ_DATA = 'SERVICES_FAQ_DATA';
export const BYOB_FAQ_DATA = 'BYOB_FAQ_DATA';

export const INIT_TRAINING = 'INIT_TRAINING';
export const INIT_RESOURCES = 'INIT_RESOURCES';

export const INIT_STATS = 'INIT_STATS';

export const CONTACT_FORM_NOTIFICATION = 'CONTACT_FORM_NOTIFICATION';
export const CONTACT_FORM_NOTIFICATION_ERROR = 'CONTACT_FORM_NOTIFICATION_ERROR';

export const SPARK_ACADEMY_FAQ = 'SPARK_ACADEMY_FAQ';