export const INIT_TEAM_MEMBERS = "INIT_TEAM_MEMBERS";
export const INIT_BOARD_MEMBERS = "INIT_BOARD_MEMBERS";
export const INIT_BYOB_SPEAKERS = "INIT_BYOB_SPEAKERS";

export const TOGGLE_MENU = "TOGGLE_MENU";

export const INIT_POSTS = 'INIT_POSTS';

export const INIT_EVENTS = "INIT_EVENTS";
export const SEARCH_EVENTS = "SEARCH_EVENTS";
export const PAGINATION = "PAGINATION";
export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";

export const INIT_SUCCESS_STORIES = 'INIT_SUCCESS_STORIES';
export const INIT_FAQ = 'INIT_FAQ';